### ISSUE TITLE
get Unique Visitors

### ISSUE THREAD

**Issue by mohammad76** [shetabit/visitor#10]
how can I get Unique Visitors count of a model ?

**Comment by khanzadimahdi** [comment]
unique users can be counted by their IP and by model.

```php
// by ip
$count = Visit::distinct('ip')->count('ip');

// by user's model
$count = Visit::visitor()->count();
```

**Comment by accoustick** [comment]
Hi, 
I just put this code to my controller,  I had change **Visit** into my model.
$count = Visit::distinct('ip')->count('ip');

the models already use this code
use Shetabit\Visitor\Traits\Visitable;

then I get this error
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ip' in 'field list' (SQL: select count(distinct `ip`) as aggregate from 'mymodel' where 'pages'.'deleted_at' is null)
