### ISSUE TITLE
How can I add middleware to log automatically

### ISSUE THREAD

**Issue by Expertweblancer** [shetabit/visitor#13]
## Detailed description

Hello
I am using Laravel 7.0
composer install and migration successfully done
I wanted to add middleware to log automatically. 
I tried many times but failed
Can you give me a tip to solve this issue

## Context

I want to track the visitors on my web admin panel

## Possible implementation

middleware issue
## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 7.2, HHVM 3):
* Operating system and version (e.g. Ubuntu 19.04, Windows 10):
* Link to your project:
* ...
* ...

**Comment by khanzadimahdi** [comment]
add the below middleware into your route middlewares: 

```php
Shetabit\Visitor\Middlewares\LogVisits
```

then use `Shetabit\Visitor\Traits\Visitable` trait in all models which can be visited by users.

and use `Shetabit\Visitor\Traits\Visitor` trait in your user model.

**Comment by Expertweblancer** [comment]
http://prntscr.com/ssdkhh
http://prntscr.com/ssdkzz

And then what is the next step?
I cant still see the logs in the database visitor tables

**Comment by khanzadimahdi** [comment]
you have introduced the `visitors` middleware to Laravel's kernel.

add it on the routes that you want their logs:
for example in `routes/web.php` :

```php
Route::middleware(['visitors'])->get('/', 'exampleController@method');
```

you have imported trait in your model, then you should add use it in model like the below:

```php
class YourModel extends Model {
    use Visitable;

}
```

**Comment by Expertweblancer** [comment]
I already tried like that before
I am getting errors
This is the log file
thanks for your help 

https://www.dropbox.com/s/9g9fva3yxxunxf8/laravel.log?dl=0
hope you to help me finally

**Comment by Expertweblancer** [comment]
[2020-06-02 14:07:28] local.ERROR: Target class [App\Http\Shetabit\Visitor\Middlewares\LogVisits] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [App\\Http\\Shetabit\\Visitor\\Middlewares\\LogVisits] does not exist. at E:\\2020\\5.

**Comment by khanzadimahdi** [comment]
in your kernel, **add a back slash before middleware's path**:

```php
 'visitors' => \Shetabit\Visitor\Middlewares\LogVisits::class,
```

the error is because of that.

**Comment by Expertweblancer** [comment]
same issue
I am finding the issue

**Comment by Expertweblancer** [comment]
[2020-06-02 14:17:07] local.ERROR: Driver not selected or default driver does not exist. {"exception":"[object] (Shetabit\\Visitor\\Exceptions\\DriverNotFoundException(code: 0): Driver not selected or default driver does not exist. at E:\\2020\\5. May\\laravel-movies\\vendor\\shetabit\\visitor\\src\\Visitor.php:341)
[stacktrace]

**Comment by Expertweblancer** [comment]
Driver not selected or default driver does not exist.

**Comment by khanzadimahdi** [comment]
publish package configs:

```php
php artisan vendor:publish
```

a config file must be exists after that: `config/visitor.php`

**Comment by Expertweblancer** [comment]
I already publish vendor 
There is visitor.php in config directory

**Comment by khanzadimahdi** [comment]
have you cached configs? you need to clear cache

```php
php artisan config:clear
```

**Comment by Expertweblancer** [comment]
Wow
php artisan config:cache

**Comment by Expertweblancer** [comment]
You are great.
What is your email address or preferred communication?
If I have any project, we can work together
Thanks for your valuable time

**Comment by khanzadimahdi** [comment]
Your welcome.
my email: khanzadimahdi@gmail.com

**Comment by Thenmee** [comment]
it will be a good idea if you added this explanation to your install and config details(the setup documentation) ,good job, thank you
