### ISSUE TITLE
Call to a member function parameters() on null

### ISSUE THREAD

**Issue by sss1337xyz** [shetabit/visitor#18]
I added a line in middleware https://prnt.sc/wh2c3g

but when you go to the site gives https://prnt.sc/wh2c99

what did I do wrong?

**Comment by khanzadimahdi** [comment]
I think you have found a bug! could you fix it and send pull request?

**Comment by jayenne** [comment]
I'm getting this too. Any progress?
Laravel 8 Jetstream.

**Comment by khanzadimahdi** [comment]
hi. I fix it now.

**Comment by khanzadimahdi** [comment]
$request->route() is only null for global middleware registered in App\Http\Kernel::$middleware. To have access to the current route, instead you must register your middleware in Kernel::$routeMiddleware.
