### ISSUE TITLE
TypeError method_exists(): 

### ISSUE THREAD

**Issue by AzizAhmad147** [shetabit/visitor#23]
hi dear i use your package and i had the fllowing error 
Argument #1 ($object_or_class) must be of type object|string, null given http://localhost:8000/
when i use 
\Shetabit\Visitor\Middlewares\LogVisits::class,
in meddleware group in kernel.php

**Comment by khanzadimahdi** [comment]
could you give me more description about the problem?

**Comment by AzizAhmad147** [comment]
::method_exists
D:\xamp\htdocs\Darman\vendor\shetabit\visitor\src\Visitor.php:241

**Comment by azhidhak** [comment]
just change in  vendor\shetabit\visitor\src\Visitor.php
`if (method_exists($model, 'visitLogs')) `
to 
` if ($model!=null && method_exists($model, 'visitLogs')) `

**Comment by khanzadimahdi** [comment]
could you fix it and send pull request?
