### ISSUE TITLE
Except is not working correctly

### ISSUE THREAD

**Issue by danielreales7** [shetabit/visitor#28]
I have in except: 'except' =>  ['login','register','admin'] but it's not working correctly.

![image](https://user-images.githubusercontent.com/5383214/130201372-43579b86-120c-4b9e-a1d9-f032ee3bce93.png)

Sometimes works well and sometimes it doesn't.

Routes web:

![image](https://user-images.githubusercontent.com/5383214/130201983-21df24e2-5ee4-4c31-b8bd-2d1102b9300b.png)

And I have another file with admin routes:

![image](https://user-images.githubusercontent.com/5383214/130202055-e3b4a838-ed66-4288-b246-a744a31730aa.png)

What I can be doing wrong?

**Comment by khanzadimahdi** [comment]
I think it's because of redirection.

**Comment by khanzadimahdi** [comment]
please check the below file (middleware)

https://github.com/shetabit/visitor/blob/master/src/Middlewares/LogVisits.php

**Comment by danielreales7** [comment]
> please check the below file (middleware)
> 
> https://github.com/shetabit/visitor/blob/master/src/Middlewares/LogVisits.php

I think so... but I can't modify this file. I published the file but I have this error:

![image](https://user-images.githubusercontent.com/5383214/130449083-03329c6f-c8b6-4d53-8d54-04683f63655e.png)

How can I fix the redirect? Thank you so much!

**Comment by khanzadimahdi** [comment]
remove LogVisits middleware from your middlewares. create a new middleware and use it instead.

**Comment by danielreales7** [comment]
> remove LogVisits middleware from your middlewares. create a new middleware and use it instead.

I still don't understand why the url /admin stores me in the database.

![image](https://user-images.githubusercontent.com/5383214/130672139-b5067f61-faec-4cd0-8031-f54f2563b340.png)

Although I have commented the middleware it keeps registering events for me.

**Comment by danielreales7** [comment]
> remove LogVisits middleware from your middlewares. create a new middleware and use it instead.

Only save data when route is /admin ... is so strange. If I reload any other route within admin it doesn't save anything.

![image](https://user-images.githubusercontent.com/5383214/130673789-25b89087-99dd-440d-89af-3011fb3908ea.png)

**Comment by khanzadimahdi** [comment]
> > remove LogVisits middleware from your middlewares. create a new middleware and use it instead.
> 
> I still don't understand why the url /admin stores me in the database.
> 
> ![image](https://user-images.githubusercontent.com/5383214/130672139-b5067f61-faec-4cd0-8031-f54f2563b340.png)
> 
> Although I have commented the middleware it keeps registering events for me.

this action is impossible. have you cached your routes?

**Comment by khanzadimahdi** [comment]
you can see middleware in the below link

https://github.com/shetabit/visitor/blob/master/src/Middlewares/LogVisits.php

and we don't have any auto-registering middleware in our provider. I think this is because of Laravel's route cache.

the provider is in the below path

https://github.com/shetabit/visitor/blob/master/src/Provider/VisitorServiceProvider.php

**Comment by danielreales7** [comment]
> you can see middleware in the below link
> 
> https://github.com/shetabit/visitor/blob/master/src/Middlewares/LogVisits.php
> 
> and we don't have any auto-registering middleware in our provider. I think this is because of Laravel's route cache.
> 
> the provider is in the below path
> 
> https://github.com/shetabit/visitor/blob/master/src/Provider/VisitorServiceProvider.php

Ohhhh! I understand what is happening. In the /admin route I show the unique visits:

{{ visitor()->visit()->distinct('ip')->count('ip') }}

This shouldn't create a registry for me, right? I only want to show the unique visits.

Sorry for being so heavy.

**Comment by danielreales7** [comment]
> you can see middleware in the below link
> 
> https://github.com/shetabit/visitor/blob/master/src/Middlewares/LogVisits.php
> 
> and we don't have any auto-registering middleware in our provider. I think this is because of Laravel's route cache.
> 
> the provider is in the below path
> 
> https://github.com/shetabit/visitor/blob/master/src/Provider/VisitorServiceProvider.php

It's works correctly:

![image](https://user-images.githubusercontent.com/5383214/130678544-ec336e7b-0013-4729-9770-e9108aedd19d.png)

I think this should be the ideal operation because I would not like to log a visit to count unique visits.

Thank you so much for your help!

**Comment by khanzadimahdi** [comment]
I think its better to use `$this->request->is($yourPattern)`

https://laravel.com/docs/8.x/requests#inspecting-the-request-path

**Comment by danielreales7** [comment]
> I think its better to use `$this->request->is($yourPattern)`
> 
> https://laravel.com/docs/8.x/requests#inspecting-the-request-path

You're right, it was by following the configuration logic.
