### ISSUE TITLE
Illuminate\Contracts\Container\BindingResolutionException Target class [shetabit-visitor] does not exist.

### ISSUE THREAD

**Issue by korangcity** [shetabit/visitor#29]
سلام. پکیج رو در لوکال نصب کردم و composer dump-autoload رو هم اجرا کردم سپس
فایل  رو به هاست منتقل کردم به این ارور رسیدم
لطفا راهنمایی بفرمایید

**Comment by khanzadimahdi** [comment]
سرویس پروایدر رو به لیست سرویس های خودتون اضافه کنید

**Comment by korangcity** [comment]
> سرویس پروایدر رو به لیست سرویس های خودتون اضافه کنید

بازم جواب ندارد همان ارور
اگر بخام دستی این پکیج رو نصب کنم در هاست، چه مراحلی را باید برم؟

**Comment by khanzadimahdi** [comment]
از چه ورژن لاراولی استفاده میکنید؟

**Comment by korangcity** [comment]
> از چه ورژن لاراولی استفاده میکنید؟

از ورژن 8 استفاده میکنم. من نصب رو در لوکال انجام دادم بعد که دستور کامپوزر رو اجرا کردم فایل پکیج رو به هاست منتقل کردم و فایل کامپوزر رو هم در هاست آپدیت کردم. به نظر شما مشکل از اینه؟

**Comment by khanzadimahdi** [comment]
توی لوکال درست کار میکنه؟

**Comment by khanzadimahdi** [comment]
اگه توی لوکال درست کار میکنه باید توی سرور کامپوزر اینستال بزنید یا اینکه پوشه وندور هم منتقل کنید

**Comment by khanzadimahdi** [comment]
به علت عدم فعالیت من این ایشو رو میبندم
