### ISSUE TITLE
About except save request or route names

### ISSUE THREAD

**Issue by kingispeak** [shetabit/visitor#30]
How can except url to table ?

I checked the source code
https://github.com/shetabit/visitor/blob/master/src/Visitor.php#L238

The excluded path, just set the request to null.
But always save to table

Looking forward to feedback.

**Comment by khanzadimahdi** [comment]
sorry for being late.
could you fix it? I think it must totally exclude it and not store any logs.

**Comment by kingispeak** [comment]
> sorry for being late. could you fix it? I think it must totally exclude it and not store any logs.

I well try fix the issue.
