### ISSUE TITLE
php artisan publish vendor not working

### ISSUE THREAD

**Issue by mohsenmehri6101** [shetabit/visitor#4]
سلام من این خط کد رو زدم اما migration های مربوطه تولید نشد ؟ مشکل کجاست ؟
و اینکه چطوری میتونم اختصاصی فقط برای همین پکیج publish vendor رو اجرا کنم؟

**Comment by khanzadimahdi** [comment]
1- run `php artisan vendor:publish`
2- run `php aritsan migrate`

**Comment by mohsenmehri6101** [comment]
thanks but for me work this line :
php artisan vendor:publish --provider=Shetabit\Visitor\Provider\VisitorServiceProvider

**Comment by khanzadimahdi** [comment]
Ok so i close this issue. enjoy it. :)
