### ISSUE TITLE
Log Responses

### ISSUE THREAD

**Issue by bazl0** [shetabit/visitor#40]
Hi,

I'm new to Laravel and have successfully implemented your visitor logging to my project, so firstly thank you!

Secondly, I think it would be beneficial to add response to the logs to store any errors that might occur with users using forms etc.

Unless you have another suggestion to do this without editing vendor files?

Thanks!

**Comment by khanzadimahdi** [comment]
Hi, always adding a response to the logs makes it heavy. we can implement some methods to add response conditionally.

**Comment by bazl0** [comment]
Ahhh yes, of course, perfect!
