### ISSUE TITLE
How to solve Call to undefined method App\Models\User::online() error

### ISSUE THREAD

**Issue by Wesley-Sinde** [shetabit/visitor#42]
## Detailed description

I am new to shetabit/visitor, i was trying set it up today to see how good its is. I have a small issue or big, when i want to check users online i get an error.
```php
BadMethodCallException
Call to undefined method App\Models\User::online()
```
Someone to help what might be the issue here

## My environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* PHP 8
* laravel 9

**Comment by khanzadimahdi** [comment]
use the related trait in the user model. see docs.

**Comment by Van4kk** [comment]
I'm getting the same error, and I'm using the trait.
```
BadMethodCallException
Call to undefined method App\Models\User::online()
```

**Comment by khanzadimahdi** [comment]
@Van4kk you should use the below trait in your User model.
```php
https://github.com/shetabit/visitor/blob/master/src/Traits/CanVisit.php
```

**Comment by Van4kk** [comment]
ight, thanks ❤️
