### ISSUE TITLE
Exclude Password

### ISSUE THREAD

**Issue by mrensz49** [shetabit/visitor#46]
Hi! 
Switching package to this one. I want to use this especially in my login route. 
In a request field name  under table name:  shetabit_visits, found out that there were password were stored. 

Just thinking if how can I modified or disabled the password only for a security purposes. 
Any idea on this on how to exclude the password only?

<img width="280" alt="Capture" src="https://github.com/shetabit/visitor/assets/86271888/52938ddf-2833-4a6c-9ece-d354dbc643f8">

Thanks.

**Comment by Enaah** [comment]
The `except` entry in the `visitor.php`-config does also nothing?!
