### ISSUE TITLE
Call to undefined method Shetabit\Visitor\Drivers\UAParser::userAgent()

### ISSUE THREAD

**Issue by mokhosh** [shetabit/visitor#48]
## Detailed description

On a fresh installation, if you change the default driver from `jenssegers` to `UAParser` and you try to log a visit, you get this error:
```
Call to undefined method Shetabit\Visitor\Drivers\UAParser::userAgent()
```

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* php8.2
* macOS
* laravel sail

**Comment by khanzadimahdi** [comment]
fixed by https://github.com/shetabit/visitor/pull/55
