### ISSUE TITLE
Typo in topic

### ISSUE THREAD

**Issue by shaedrich** [shetabit/visitor#51]
## Detailed description
It appears that the topic [larave-online-users](/tags/larave-online-users), you assigned to your repository, has a typo. The correct topic, [laravel-online-users](/tags/laravel-online-users), has already been added to your repositories topics.

## Context
Having both topics, doesn't benefit the repository.

## Possible implementation
I suggest, removing the topic with the typo from your repository.

## Your environment
n/a

**Comment by khanzadimahdi** [comment]
thanks for reminding me. I fixed it.

**Comment by shaedrich** [comment]
You're welcome.
