### ISSUE TITLE
Laravel Jetstream compatability issue due to jenssegers/agent outdated dependency

### ISSUE THREAD

**Issue by bdj-Razik** [shetabit/visitor#54]
Laravel's Jetstream contributors have reworked the code base to avoid relying on the jenssegers/agent package that doesn't get maintained any more and instead uses the latest mobiledetect/mobiledetectlib.

  Problem 1
    - jenssegers/agent[v2.6.0, ..., v2.6.4] require mobiledetect/mobiledetectlib ^2.7.6 -> found mobiledetect/mobiledetectlib[2.7.6, ..., 2.8.45] but the package is fixed to 4.8.04 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - shetabit/visitor v4.1.0 requires jenssegers/agent ^2.6 -> satisfiable by jenssegers/agent[v2.6.0, ..., v2.6.4].
    - Root composer.json requires shetabit/visitor ^4.1 -> satisfiable by shetabit/visitor[v4.1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require shetabit/visitor:*" to figure out if any version is installable, or "composer require shetabit/visitor:^2.1" if you know which you need.

**Comment by khanzadimahdi** [comment]
could you please create a PR?

**Comment by Linedev-Web** [comment]
Here's the PR to get Visitor working for Laravel 11.
Please note that the package will no longer work for Laravel versions 5-6-7-8.
Php >= 8
Link: https://github.com/shetabit/visitor/pull/58

**Comment by khanzadimahdi** [comment]
A new version released, please rely on v4.3.0
