### ISSUE TITLE
Can you update for laravel 11 compatibility

### ISSUE THREAD

**Issue by sidewaysglance** [shetabit/visitor#56]
I'm trying to update my laravel app and one of the issues is that shetabit/visitor is not updated.

**Comment by khanzadimahdi** [comment]
right, could you please update the package dependencies to support laravel 11 and create a PR ?

**Comment by Linedev-Web** [comment]
Hi, I've just created a PR to update the composer.json for Laravel11.
Link: https://github.com/shetabit/visitor/pull/57

**Comment by sidewaysglance** [comment]
Thanks you for doing this @Linedev-Web.

@khanzadimahdi - can you merge please?
