### ISSUE TITLE
Recording visitor_id for User models with UUID is missing or not documented

### ISSUE THREAD

**Issue by dlogic-lbs** [shetabit/visitor#60]
The title of this issue speaks for itself - the package does not work for logged in users with the User model using UUIDs and not just simple integer IDs. This to me is a really big mistake and something I would expect from any modern and professional package to tackle. If it does, then it is not documented and you should create docs for that too. I will surely find a way around this as I'm a developer, but to me this is an issue (and for others I assume). Thanks.

**Comment by Van4kk** [comment]
Just add this to your User model

```php
/**
 * The "type" of the primary key ID.
 *
 * @var string
 */
protected $keyType = 'string';

/**
 * Indicates if the IDs are auto-incrementing.
 *
 * @var bool
 */
public $incrementing = false;
```

**Comment by dlogic-lbs** [comment]
If you dont understand english well enough to understand what I said, then dont comment. I did NOT say I didnt know, how to use UUIDs in my models, I said the package does not support UUIDs out of the box, I fixed this as Im a pro and I simply added a migration for this shetabit packages table(s) so to change the used int ids to uuids, all I was saying is that for a package these days to only assume int ids is bit unprofessional. Do not respond, when you dont understand the comment.

**Comment by Van4kk** [comment]
You clearly have some brain damage.

**Comment by dlogic-lbs** [comment]
I have brain damage? You cannot even read, let alone you give me completely irrelevant and not to the topic "advice" (one that a child could Google by the way), and Im the one with brain damage? 

I was commenting on the poor assumptions this package has been using - by not supporting UUIDs, thats my opinion and Im sure of many others. I was NOT asking for any advice for how to use UUIDs, and the fact you still choose to come back and pretend Im the weird one here just speaks volumes about you, everyone reading these comments sees that you have some sort of issue.

Anyone with half a brain would simply just say "oh, right, I didnt read your comment well enough" or "yeah, right, my bad", only childish unprofessional wanna-be devs that think that by pasting something simple and not even related to a comment will make them feel better about themselves.

You should not comment, period. You dont belong to the industry if you cannot even read. Period.
